# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set the correct JDK(15.0.1)
      uses: actions/setup-java@v1
      with:
        java-version: 15.0.1
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Grant execute permission for gradlew and install openjfx
      run:  chmod +x gradlew
    - name: Install xvfb
      run: sudo apt-get install xvfb
    - name: Install npm
      run: npm install
    - name: Install openjfk
      run:  sudo apt install openjfx
    - name: Export variable
      run:  export DISPLAY=:99.0

    - name: Before
      run: |
           - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
           - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
           - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
           - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.lock

    - name: Build with Gradle
      run: ./gradlew build
