# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set the correct JDK(15.0.1)
      uses: actions/setup-java@v1
      with:
        java-version: 15.0.1
    - name: Grant execute permission for gradlew and install openjfx
      run:  chmod +x gradlew
    - name: Install xvfb
      run: sudo apt-get install xvfb
    - name: Install npm
      run: sudo apt-get install npm
    - name: Test npm
      run:  xvfb-run --auto-servernum npm test
    - name: Update system
      run: sudo apt update
    - name: Install openjfk
      run:  sudo apt install openjfx
    - name: Export variable
      run:  export DISPLAY=:99.0
    - name: Build with Gradle
      run: ./gradlew build
